"""add mining master entities layer 1

Revision ID: f0204a22baa6
Revises: c5f89727c115
Create Date: 2025-12-21 01:13:19.480235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0204a22baa6'
down_revision = 'c5f89727c115'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('genetic_model', sa.String(length=100), nullable=True),
    sa.Column('primary_commodity', sa.String(length=50), nullable=False),
    sa.Column('secondary_commodity', sa.String(length=50), nullable=True),
    sa.Column('measured_resources_mt', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('indicated_resources_mt', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('inferred_resources_mt', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('proven_reserves_mt', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('probable_reserves_mt', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('avg_cu_grade_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('avg_mo_grade_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('commune', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Yacimientos mineros con clasificación geológica y recursos'
    )
    op.create_index('idx_deposits_code', 'deposits', ['code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_deposits_country_region', 'deposits', ['country', 'region'], unique=False)
    op.create_index('idx_deposits_name', 'deposits', ['name'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_deposits_code'), 'deposits', ['code'], unique=True)
    op.create_index(op.f('ix_deposits_name'), 'deposits', ['name'], unique=False)
    op.create_table('equipment_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('HAUL_TRUCK', 'EXCAVATOR', 'LOADER', 'DRILL', 'CRUSHER', 'MILL', 'FLOTATION_CELL', 'PUMP', 'CONVEYOR', 'CYCLONE', 'THICKENER', 'FILTER', name='equipment_category_enum'), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=20), nullable=True),
    sa.Column('power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_life_hours', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Catálogo de tipos de equipos mineros e industriales'
    )
    op.create_index('idx_equipment_types_category', 'equipment_types', ['category'], unique=False)
    op.create_index('idx_equipment_types_code', 'equipment_types', ['code'], unique=False)
    op.create_index('idx_equipment_types_manufacturer', 'equipment_types', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_equipment_types_code'), 'equipment_types', ['code'], unique=True)
    op.create_table('reagents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('commercial_name', sa.String(length=255), nullable=True),
    sa.Column('reagent_type', sa.String(length=50), nullable=False),
    sa.Column('chemical_family', sa.String(length=100), nullable=True),
    sa.Column('chemical_formula', sa.String(length=100), nullable=True),
    sa.Column('molecular_weight', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('density', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('recommended_dosage_min', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('recommended_dosage_max', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('dosage_unit', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=True),
    sa.Column('cost_unit', sa.String(length=20), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('supplier_code', sa.String(length=100), nullable=True),
    sa.Column('hazard_class', sa.String(length=50), nullable=True),
    sa.Column('storage_requirements', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('recommended_dosage_max >= recommended_dosage_min', name='reagents_dosage_max_gte_min'),
    sa.CheckConstraint('recommended_dosage_min >= 0', name='reagents_dosage_min_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='reagents_unit_cost_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    comment='Catálogo de reactivos químicos para proceso de flotación'
    )
    op.create_index('idx_reagents_chemical_family', 'reagents', ['chemical_family'], unique=False)
    op.create_index('idx_reagents_code', 'reagents', ['code'], unique=False)
    op.create_index('idx_reagents_is_active', 'reagents', ['is_active'], unique=False)
    op.create_index('idx_reagents_reagent_type', 'reagents', ['reagent_type'], unique=False)
    op.create_index(op.f('ix_reagents_code'), 'reagents', ['code'], unique=True)
    op.create_table('coordinates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_id', sa.UUID(), nullable=False),
    sa.Column('point_type', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=7), nullable=False),
    sa.Column('elevation_masl', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('utm_zone', sa.String(length=10), nullable=True),
    sa.Column('utm_easting', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('utm_northing', sa.Numeric(precision=13, scale=3), nullable=True),
    sa.Column('coordinate_system', sa.String(length=50), nullable=False),
    sa.Column('datum', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='coordinates_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='coordinates_longitude_range'),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Coordenadas geoespaciales de yacimientos y puntos de interés'
    )
    op.create_index('idx_coordinates_deposit_id', 'coordinates', ['deposit_id'], unique=False)
    op.create_index('idx_coordinates_lat_lon', 'coordinates', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_coordinates_point_type', 'coordinates', ['point_type'], unique=False)
    op.create_index(op.f('ix_coordinates_deposit_id'), 'coordinates', ['deposit_id'], unique=False)
    op.create_table('mineralogy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_id', sa.UUID(), nullable=False),
    sa.Column('mineral_name', sa.String(length=100), nullable=False),
    sa.Column('mineral_formula', sa.String(length=50), nullable=True),
    sa.Column('mineral_class', sa.String(length=50), nullable=False),
    sa.Column('abundance_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_primary_ore', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('floatability', sa.String(length=20), nullable=True),
    sa.Column('natural_hydrophobicity', sa.Boolean(), nullable=True),
    sa.Column('associated_minerals', sa.Text(), nullable=True),
    sa.Column('gangue_association', sa.Text(), nullable=True),
    sa.Column('arsenic_content_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('antimony_content_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bismuth_content_ppm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('abundance_pct >= 0 AND abundance_pct <= 100', name='mineralogy_abundance_range'),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Composición mineralógica de yacimientos con propiedades de flotación'
    )
    op.create_index('idx_mineralogy_deposit_id', 'mineralogy', ['deposit_id'], unique=False)
    op.create_index('idx_mineralogy_is_primary_ore', 'mineralogy', ['is_primary_ore'], unique=False)
    op.create_index('idx_mineralogy_mineral_class', 'mineralogy', ['mineral_class'], unique=False)
    op.create_index('idx_mineralogy_mineral_name', 'mineralogy', ['mineral_name'], unique=False)
    op.create_index(op.f('ix_mineralogy_deposit_id'), 'mineralogy', ['deposit_id'], unique=False)
    op.create_table('mines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deposit_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mine_type', sa.Enum('OPEN_PIT', 'UNDERGROUND', 'MIXED', name='mine_type_enum'), nullable=False),
    sa.Column('design_capacity_tpd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current_capacity_tpd', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_capacity_tpd >= 0', name='mines_current_capacity_non_negative'),
    sa.CheckConstraint('design_capacity_tpd > 0', name='mines_design_capacity_positive'),
    sa.ForeignKeyConstraint(['deposit_id'], ['deposits.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Operaciones mineras asociadas a yacimientos'
    )
    op.create_index('idx_mines_code', 'mines', ['code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_mines_deposit_id', 'mines', ['deposit_id'], unique=False)
    op.create_index('idx_mines_is_active', 'mines', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_mines_code'), 'mines', ['code'], unique=True)
    op.create_index(op.f('ix_mines_deposit_id'), 'mines', ['deposit_id'], unique=False)
    op.create_index(op.f('ix_mines_name'), 'mines', ['name'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipment_type_id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('OPERATIONAL', 'MAINTENANCE', 'FAILED', 'STANDBY', 'DECOMMISSIONED', name='equipment_status_enum'), nullable=False),
    sa.Column('location_area', sa.String(length=100), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('installation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_operating_hours', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hours_since_last_overhaul', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('acquisition_currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('acquisition_cost >= 0', name='equipment_acquisition_cost_non_negative'),
    sa.CheckConstraint('total_operating_hours >= 0', name='equipment_operating_hours_non_negative'),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Equipos físicos de la operación minera con tracking de horas y mantenimiento'
    )
    op.create_index('idx_equipment_code', 'equipment', ['code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_equipment_location', 'equipment', ['location_area'], unique=False)
    op.create_index('idx_equipment_mine_id', 'equipment', ['mine_id'], unique=False)
    op.create_index('idx_equipment_status', 'equipment', ['status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_equipment_type_id', 'equipment', ['equipment_type_id'], unique=False)
    op.create_index(op.f('ix_equipment_code'), 'equipment', ['code'], unique=True)
    op.create_index(op.f('ix_equipment_equipment_type_id'), 'equipment', ['equipment_type_id'], unique=False)
    op.create_index(op.f('ix_equipment_mine_id'), 'equipment', ['mine_id'], unique=False)
    op.create_table('mine_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('design_tonnage_mt', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('design_cu_grade_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('design_mo_grade_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('design_strip_ratio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('elevation_top_masl', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('elevation_bottom_masl', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('design_cu_grade_pct >= 0 AND design_cu_grade_pct <= 100', name='mine_phases_cu_grade_range'),
    sa.CheckConstraint('design_mo_grade_pct >= 0 AND design_mo_grade_pct <= 100', name='mine_phases_mo_grade_range'),
    sa.CheckConstraint('sequence_number > 0', name='mine_phases_sequence_positive'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Fases de explotación minera con parámetros de diseño'
    )
    op.create_index('idx_mine_phases_code', 'mine_phases', ['code'], unique=False)
    op.create_index('idx_mine_phases_mine_id', 'mine_phases', ['mine_id'], unique=False)
    op.create_index('idx_mine_phases_sequence', 'mine_phases', ['mine_id', 'sequence_number'], unique=False)
    op.create_index(op.f('ix_mine_phases_code'), 'mine_phases', ['code'], unique=False)
    op.create_index(op.f('ix_mine_phases_mine_id'), 'mine_phases', ['mine_id'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('default_shift', sa.Enum('DAY', 'NIGHT', 'SWING', name='shift_type_enum'), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Operadores de equipos en la operación minera'
    )
    op.create_index('idx_operators_employee_code', 'operators', ['employee_code'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_operators_is_active', 'operators', ['is_active'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_operators_job_title', 'operators', ['job_title'], unique=False)
    op.create_index('idx_operators_mine_id', 'operators', ['mine_id'], unique=False)
    op.create_index('idx_operators_name', 'operators', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_operators_employee_code'), 'operators', ['employee_code'], unique=True)
    op.create_index(op.f('ix_operators_mine_id'), 'operators', ['mine_id'], unique=False)
    op.create_table('process_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=False),
    sa.Column('parent_area_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area_type', sa.Enum('CRUSHING', 'GRINDING', 'ROUGHER', 'CLEANER', 'SCAVENGER', 'REGRIND', 'SELECTIVE', 'THICKENING', 'FILTRATION', name='process_area_type_enum'), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('design_capacity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=20), nullable=True),
    sa.Column('target_recovery_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_grade_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('circuit_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence_order > 0', name='process_areas_sequence_positive'),
    sa.CheckConstraint('target_grade_pct >= 0 AND target_grade_pct <= 100', name='process_areas_grade_range'),
    sa.CheckConstraint('target_recovery_pct >= 0 AND target_recovery_pct <= 100', name='process_areas_recovery_range'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_area_id'], ['process_areas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Áreas de proceso de la planta concentradora'
    )
    op.create_index('idx_process_areas_area_type', 'process_areas', ['area_type'], unique=False)
    op.create_index('idx_process_areas_code', 'process_areas', ['code'], unique=False)
    op.create_index('idx_process_areas_mine_id', 'process_areas', ['mine_id'], unique=False)
    op.create_index('idx_process_areas_parent', 'process_areas', ['parent_area_id'], unique=False)
    op.create_index('idx_process_areas_sequence', 'process_areas', ['mine_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_process_areas_code'), 'process_areas', ['code'], unique=False)
    op.create_index(op.f('ix_process_areas_mine_id'), 'process_areas', ['mine_id'], unique=False)
    op.create_index(op.f('ix_process_areas_parent_area_id'), 'process_areas', ['parent_area_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mine_phase_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('block_i', sa.Integer(), nullable=False),
    sa.Column('block_j', sa.Integer(), nullable=False),
    sa.Column('block_k', sa.Integer(), nullable=False),
    sa.Column('centroid_x', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('centroid_y', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('centroid_z', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('size_x', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('size_y', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('size_z', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('tonnage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('density', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('cu_grade_pct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('mo_grade_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('au_grade_gpt', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('ag_grade_gpt', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('mineral_type', sa.Enum('SULFIDE', 'OXIDE', 'MIXED', 'TRANSITION', name='mineral_type_enum'), nullable=True),
    sa.Column('is_mined', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cu_grade_pct >= 0 AND cu_grade_pct <= 100', name='blocks_cu_grade_range'),
    sa.CheckConstraint('density > 0', name='blocks_density_positive'),
    sa.CheckConstraint('mo_grade_pct >= 0 AND mo_grade_pct <= 100', name='blocks_mo_grade_range'),
    sa.CheckConstraint('tonnage >= 0', name='blocks_tonnage_non_negative'),
    sa.ForeignKeyConstraint(['mine_phase_id'], ['mine_phases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Bloques del modelo de bloques para planificación minera'
    )
    op.create_index('idx_blocks_code', 'blocks', ['code'], unique=False)
    op.create_index('idx_blocks_is_mined', 'blocks', ['is_mined'], unique=False)
    op.create_index('idx_blocks_mine_phase_id', 'blocks', ['mine_phase_id'], unique=False)
    op.create_index('idx_blocks_mineral_type', 'blocks', ['mineral_type'], unique=False)
    op.create_index('idx_blocks_position', 'blocks', ['mine_phase_id', 'block_i', 'block_j', 'block_k'], unique=False)
    op.create_index(op.f('ix_blocks_code'), 'blocks', ['code'], unique=False)
    op.create_index(op.f('ix_blocks_mine_phase_id'), 'blocks', ['mine_phase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_mine_phase_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_code'), table_name='blocks')
    op.drop_index('idx_blocks_position', table_name='blocks')
    op.drop_index('idx_blocks_mineral_type', table_name='blocks')
    op.drop_index('idx_blocks_mine_phase_id', table_name='blocks')
    op.drop_index('idx_blocks_is_mined', table_name='blocks')
    op.drop_index('idx_blocks_code', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_process_areas_parent_area_id'), table_name='process_areas')
    op.drop_index(op.f('ix_process_areas_mine_id'), table_name='process_areas')
    op.drop_index(op.f('ix_process_areas_code'), table_name='process_areas')
    op.drop_index('idx_process_areas_sequence', table_name='process_areas')
    op.drop_index('idx_process_areas_parent', table_name='process_areas')
    op.drop_index('idx_process_areas_mine_id', table_name='process_areas')
    op.drop_index('idx_process_areas_code', table_name='process_areas')
    op.drop_index('idx_process_areas_area_type', table_name='process_areas')
    op.drop_table('process_areas')
    op.drop_index(op.f('ix_operators_mine_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_employee_code'), table_name='operators')
    op.drop_index('idx_operators_name', table_name='operators')
    op.drop_index('idx_operators_mine_id', table_name='operators')
    op.drop_index('idx_operators_job_title', table_name='operators')
    op.drop_index('idx_operators_is_active', table_name='operators', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_operators_employee_code', table_name='operators', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('operators')
    op.drop_index(op.f('ix_mine_phases_mine_id'), table_name='mine_phases')
    op.drop_index(op.f('ix_mine_phases_code'), table_name='mine_phases')
    op.drop_index('idx_mine_phases_sequence', table_name='mine_phases')
    op.drop_index('idx_mine_phases_mine_id', table_name='mine_phases')
    op.drop_index('idx_mine_phases_code', table_name='mine_phases')
    op.drop_table('mine_phases')
    op.drop_index(op.f('ix_equipment_mine_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_code'), table_name='equipment')
    op.drop_index('idx_equipment_type_id', table_name='equipment')
    op.drop_index('idx_equipment_status', table_name='equipment', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_equipment_mine_id', table_name='equipment')
    op.drop_index('idx_equipment_location', table_name='equipment')
    op.drop_index('idx_equipment_code', table_name='equipment', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('equipment')
    op.drop_index(op.f('ix_mines_name'), table_name='mines')
    op.drop_index(op.f('ix_mines_deposit_id'), table_name='mines')
    op.drop_index(op.f('ix_mines_code'), table_name='mines')
    op.drop_index('idx_mines_is_active', table_name='mines', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_mines_deposit_id', table_name='mines')
    op.drop_index('idx_mines_code', table_name='mines', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('mines')
    op.drop_index(op.f('ix_mineralogy_deposit_id'), table_name='mineralogy')
    op.drop_index('idx_mineralogy_mineral_name', table_name='mineralogy')
    op.drop_index('idx_mineralogy_mineral_class', table_name='mineralogy')
    op.drop_index('idx_mineralogy_is_primary_ore', table_name='mineralogy')
    op.drop_index('idx_mineralogy_deposit_id', table_name='mineralogy')
    op.drop_table('mineralogy')
    op.drop_index(op.f('ix_coordinates_deposit_id'), table_name='coordinates')
    op.drop_index('idx_coordinates_point_type', table_name='coordinates')
    op.drop_index('idx_coordinates_lat_lon', table_name='coordinates')
    op.drop_index('idx_coordinates_deposit_id', table_name='coordinates')
    op.drop_table('coordinates')
    op.drop_index(op.f('ix_reagents_code'), table_name='reagents')
    op.drop_index('idx_reagents_reagent_type', table_name='reagents')
    op.drop_index('idx_reagents_is_active', table_name='reagents')
    op.drop_index('idx_reagents_code', table_name='reagents')
    op.drop_index('idx_reagents_chemical_family', table_name='reagents')
    op.drop_table('reagents')
    op.drop_index(op.f('ix_equipment_types_code'), table_name='equipment_types')
    op.drop_index('idx_equipment_types_manufacturer', table_name='equipment_types')
    op.drop_index('idx_equipment_types_code', table_name='equipment_types')
    op.drop_index('idx_equipment_types_category', table_name='equipment_types')
    op.drop_table('equipment_types')
    op.drop_index(op.f('ix_deposits_name'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_code'), table_name='deposits')
    op.drop_index('idx_deposits_name', table_name='deposits', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_deposits_country_region', table_name='deposits')
    op.drop_index('idx_deposits_code', table_name='deposits', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('deposits')
    # ### end Alembic commands ###
